# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NonceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_key', models.CharField(max_length=200)),
                ('timestamp', models.IntegerField()),
                ('nonce', models.CharField(max_length=200)),
            ],
        ),
    ]
